In [10]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [11]:
print(x[:,2])

[3 6]


In [12]:
c=np.array([[[1,2,3],[4,5,6]],[7,8,9]])
print(c)

[list([[1, 2, 3], [4, 5, 6]]) list([7, 8, 9])]


In [13]:
c=np.array([ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]  ])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
print(c[0,0])

[1 2 3]


In [15]:
print(c[0,0,0])

1


In [16]:
print(c[4,0,0])

IndexError: index 4 is out of bounds for axis 0 with size 2

In [17]:
print(c[3,0,0])

IndexError: index 3 is out of bounds for axis 0 with size 2

In [18]:
print(c[0])

[[1 2 3]
 [4 5 6]]


In [19]:
print(c[1])

[[ 7  8  9]
 [10 11 12]]


In [20]:
print(c[0,2])

IndexError: index 2 is out of bounds for axis 1 with size 2

In [21]:
print(c[0][2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [23]:
print(c[0,1])

[4 5 6]


In [24]:
print(c[0,0])

[1 2 3]


In [25]:
print(c[0][1])

[4 5 6]


In [26]:
print(c[0,1,2])

6


In [27]:
print(c[:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
print(c[:,1])

[[ 4  5  6]
 [10 11 12]]


In [29]:
print(c[:,1,1])

[ 5 11]


In [30]:
#this was the slicing operation ie. using : colon operator

In [31]:
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)
print(c.nbytes)

(2, 2, 3)
3
12
int32
48


In [32]:
#transpose

In [33]:
print(c.T)

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [34]:
v=c.T
print(v.size)

12


In [35]:
print(v.shape)

(3, 2, 2)


In [36]:
##NUmpy constants

In [38]:
print(np.NINF)
print(np.NAN)
print(np.inf)
print(np.NZERO)
print(np.PZERO)
print(np.e)
print(np.euler_gamma)
print(np.pi)

-inf
nan
inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


In [39]:
#ones and zeroes

In [46]:
print(np.eye(3,3,dtype=np.uint8))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [47]:
print(np.eye(3,3,dtype=np.uint8,k=1))

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [48]:
#similarly identity,ones,zeros,full

In [51]:
print(np.ones((2,3,3),dtype=np.uint8))

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [52]:
print(np.full((2,3,3),dtype=np.uint8,fill_value=2))

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]


In [53]:
#matrices