In [79]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [80]:
print(x[:,2])

[3 6]


In [81]:
c=np.array([[[1,2,3],[4,5,6]],[7,8,9]])
print(c)

[list([[1, 2, 3], [4, 5, 6]]) list([7, 8, 9])]


In [82]:
c=np.array([ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]  ])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [83]:
print(c[0,0])

[1 2 3]


In [84]:
print(c[0,0,0])

1


In [85]:
print(c[4,0,0])

IndexError: index 4 is out of bounds for axis 0 with size 2

In [86]:
print(c[3,0,0])

IndexError: index 3 is out of bounds for axis 0 with size 2

In [87]:
print(c[0])

[[1 2 3]
 [4 5 6]]


In [88]:
print(c[1])

[[ 7  8  9]
 [10 11 12]]


In [89]:
print(c[0,2])

IndexError: index 2 is out of bounds for axis 1 with size 2

In [90]:
print(c[0][2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [91]:
print(c[0,1])

[4 5 6]


In [92]:
print(c[0,0])

[1 2 3]


In [93]:
print(c[0][1])

[4 5 6]


In [94]:
print(c[0,1,2])

6


In [95]:
print(c[:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [96]:
print(c[:,1])

[[ 4  5  6]
 [10 11 12]]


In [97]:
print(c[:,1,1])

[ 5 11]


In [98]:
#this was the slicing operation ie. using : colon operator

In [99]:
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)
print(c.nbytes)

(2, 2, 3)
3
12
int32
48


In [100]:
#transpose

In [101]:
print(c.T)

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [102]:
v=c.T
print(v.size)

12


In [103]:
print(v.shape)

(3, 2, 2)


In [104]:
##NUmpy constants

In [105]:
print(np.NINF)
print(np.NAN)
print(np.inf)
print(np.NZERO)
print(np.PZERO)
print(np.e)
print(np.euler_gamma)
print(np.pi)

-inf
nan
inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


In [106]:
#ones and zeroes

In [107]:
print(np.eye(3,3,dtype=np.uint8))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [108]:
print(np.eye(3,3,dtype=np.uint8,k=1))

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [109]:
#similarly identity,ones,zeros,full

In [110]:
print(np.ones((2,3,3),dtype=np.uint8))

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [111]:
print(np.full((2,3,3),dtype=np.uint8,fill_value=2))

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]


In [112]:
#matrices

In [113]:
print(np.tri(3,3,dtype=np.uint16,k=1))

[[1 1 0]
 [1 1 1]
 [1 1 1]]


In [114]:
z=(np.tri(3,3,dtype=np.uint16,k=1))
print(z);

[[1 1 0]
 [1 1 1]
 [1 1 1]]


In [115]:
y=np.tril(z)
print(y)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [116]:
y=np.triu(z,k=1)
print(y)

[[0 1 0]
 [0 0 1]
 [0 0 0]]
