In [1]:
%matplotlib inline
import numpy as np

In [2]:
x=np.arange(start=0,stop=10,step=1)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
y=x.reshape((5,2))
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
x=np.array([[1,1,2],[2,4,5]],dtype=np.uint16)
print(x)

[[1 1 2]
 [2 4 5]]


In [6]:
y=np.reshape(x,6)
print(y)

[1 1 2 2 4 5]


In [7]:
y=np.ravel(x)
print(y)

[1 1 2 2 4 5]


In [11]:
y=x.flatten() #flatten is not a module in numpy #'C' can also be used in flatten(),it would result the same
print(y)

[1 1 2 2 4 5]


In [12]:
y=x.flatten('F') #column wise print
print(y)

[1 2 1 4 2 5]


In [13]:
z=np.stack([x,y])
print(z)

ValueError: all input arrays must have the same shape

In [14]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.stack([x,y])
print(z)

[[1 2 3]
 [4 5 6]]


In [16]:
z=np.stack([x,y],axis=-1) #np.dstack()...depthwise stacking
print(z)
print(z.shape)#l,b,h #this is 2d

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [18]:
z=np.dstack([x,y]) #np.hstack() ,np.vstack()
print(z)
print(z.shape)#l,b,h #this is 3d

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [21]:
f=np.arange(start=2,stop=20,step=2)
print(f)

[ 2  4  6  8 10 12 14 16 18]


In [23]:
a,b,c=np.split(f,3)#works only if equal spaces are present in the original array
print(a,b,c)

[2 4 6] [ 8 10 12] [14 16 18]


In [24]:
k=np.random.rand(2,2)
print(k)
print(np.split(k,2))

[[0.31718398 0.6089148 ]
 [0.80453139 0.21998456]]
[array([[0.31718398, 0.6089148 ]]), array([[0.80453139, 0.21998456]])]


In [ ]:
#similarly we have dsplit,hsplit,vsplit