In [ ]:
#bitwise operations

In [2]:
import numpy as np

In [10]:
x=np.array([1,2,1],dtype=np.uint8)
y=np.array([0,1,0],dtype=np.uint8)
print(x,y)
print(np.bitwise_and(x,y))
print(np.bitwise_or(x,y))
print(np.bitwise_xor(x,y))
print(np.bitwise_not(x))

[1 2 1] [0 1 0]
[0 0 0]
[1 3 1]
[1 3 1]
[254 253 254]


In [11]:
#statistical functions

In [16]:
print(np.median(x))
print(np.average(x)) 
print(format(np.average(x),'3f'))
print(round(np.average(x),3))

1.0
1.3333333333333333
1.333333
1.333


In [17]:
#simalarly  np.mean,np.std(std deviation),np.var(variance)

In [18]:
print(np.histogram(x)) #it gives array of frequency and ranges  

(array([2, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64), array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ]))


In [19]:
# trying on 2d array

In [20]:
c=np.array([[1,2,3],[4,5,6]],np.uint8)
print(c)

[[1 2 3]
 [4 5 6]]


In [21]:
print(np.median(c))
print(np.average(c)) 
print(format(np.average(c),'3f'))
print(round(np.average(c),3))
print(np.histogram(c))

3.5
3.5
3.500000
3.5
(array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=int64), array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ]))
